server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/test?serverTimezone=Asia/Seoul?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Entity column naming -> (userName = user_name)
    properties:
      hibernate:
        show_sql: false
        format_sql: true

logging:
  level:
    org.hibernate.SQL: error
    org.hibernate.type: error